version: '3'
networks:
   composeNet:
volumes:
   db_data:
services:
   db:
      image: mysql:5.7
      volumes:
       - ./db_data:/var/lib/mysql
      environment:
       - MYSQL_ROOT_PASSWORD=mysql
       - MYSQL_USER=wordpress
       - MYSQL_PASSWORD=wordpress
       - MYSQL_DATABASE=wordpress
      networks:
       - composeNet
   wordpress:
      depends_on:
       - db
      image: wordpress:latest
      ports:
       - "80:80"
      environment:
       - WORDPRESS_DB_HOST=db:3306
       - WORDPRESS_DB_USER=wordpress
       - WORDPRESS_DB_PASSWORD=wordpress
      networks:
       - composeNet
