version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx.docker.local
    volumes:
      - conf:/etc/nginx
    ports:
     - 80:80
     - 443:443
    networks:
     - appnet
    restart: always
volumes:
  conf:
networks:
  appnet:
    external: true
