version: '3'
networks:
   composeNet:
services:
   db:
      image: mysql:5.7
      hostname: mysql
      volumes:
       - ./volumes/db/var/lib/mysql:/var/lib/mysql
      hostname: db
      environment:
       - MYSQL_ROOT_PASSWORD=mysql
       - MYSQL_DATABASE=glpi
       - MYSQL_USER=glpi
       - MYSQL_PASSWORD=glpi
      networks:
       - composeNet
   glpi:
      depends_on:
       - db
      image: everaldomaestro/glpi:9.2
      hostname: glpi       
      ports:
       - 80:80
      networks:
       - composeNet
