version: '3'
networks:
   composeNet:
volumes:
   zbx_db_pgsql:
services:
   db:
      image: postgres:9.3
      volumes:
       - ./zbx_db_pgsql:/var/lib/postgresql/data
      environment:
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DB=zabbix
      networks:
       - composeNet
   server:
      depends_on:
       - db
      image: everaldomaestro/zabbix-server-pgsql:ubuntu-3.4.3
      ports:
       - "10051:10051"
      environment:
       - DB_SERVER_HOST=db
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
      networks:
       - composeNet
   web:
      depends_on:
       - db
       - server
      image: zabbix/zabbix-web-nginx-pgsql:ubuntu-3.4.3
      ports:
       - "80:80"
       - "443:443"
      environment:
       - ZBX_SERVER_HOST=server
       - DB_SERVER_HOST=db
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - PHP_TZ="America/Recife"
      networks:
       - composeNet
